<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>NDOP administration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link href="<?php echo $this->asset('assets/css/layout.css') ?>" rel="stylesheet">
    
    <link href="<?= $this->asset('assets/css/masonry.css') ?>" rel="stylesheet">
    <link href="<?= $this->asset('assets/css/module_viewer.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->asset('assets/css/module_editor.css') ?>" rel="stylesheet">

    <script src="<?php echo $this->asset('assets/js/jquery-2.0.2.min.js') ?>"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="menu">
          <a class="brand" href="<?= $this->url('/') ?>">NDOP administration page</a>
          <ul class="nav">
            <li class="<?php echo $this['home_page'] ?>">
              <a href="<?= $this->url('/') ?>">Home</a>
            </li>
            <li class="<?php echo $this['config_page'] ?>">
              <a href="<?= $this->url('config') ?>">Configuration</a>
            </li>
            <?php if($this['database']){ ?>
            <li class="<?php echo $this['layout_page'] ?>">
              <a href="<?= $this->url('layout') ?>">Layout</a>
            </li>
            <li class="<?php echo $this['modules_page'] ?>">
              <a href="<?= $this->url('modules') ?>">Modules</a>
            </li>
            <li class="<?php echo $this['widgets_page'] ?>">
              <a href="<?= $this->url('widgets') ?>">Widget</a>
            </li>
            <?php } ?>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <?php if (count($this['flash_messages'])): ?>
        <?php foreach ($this['flash_messages'] as $label => $messages): ?>
          <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?php echo $label ?>"><?php echo $message ?></li>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php endif ?>
    
      <div id="content">
        <?php echo $contentForLayout; ?>
      </div>
    </div>
  </body>
</html>
