
<div class="hero-unit">
  <h1><strong>Configuration</strong></h1>
  <p>Fill in the form with your configuration. </p>
</div>
<div>
	<h2>Database configuration</h2>
	<div class='alert <?= $database_state ?>' >
		<?php if($database_connection){ ?>
		Your database is correctly configured, you can continue.
		<?php }elseif($database_info){ ?>
		Infomations you provided to access the database are not correct, please retry. Check the IP of the machine which host your database programm and check that the user you provided has enough priviliges to create a database, and select, insert, update in it.
		<?php }else{ ?>
		Please fill in the form.
		<?php } ?>


		<div class="accordion" id="accordion1">
			<div class="accordion-group">
				<form action="<?= $this->url('config_database') ?>" method="POST">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne">
							Database form
						</a>
					</div>
					<div id="collapseOne" class="accordion-body collapse <?php if(!$database_connection){echo 'in';} ?>">
						<div class="accordion-inner">
							<label>Adress</label>
							<input name="database_address" type="text" placeholder="Ip of your database server" value='<?= $database_address ?>'>
							<span class="help-block">Ex: 192.168.1.15 or www.myhostname.com</span>

							<label>Login</label>
							<input name="database_login"type="text" placeholder="Login of your database server" value='<?= $database_login ?>'>
							<span class="help-block">Ex: mydatabaselogin</span>

							<label>Password</label>
							<input name="database_password"type="password" placeholder="Password of your database server" value='<?= $database_password ?>'>
							<span class="help-block">Ex: mydatabasepassword</span>

							<button type="submit" class="btn">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>


	</div>

	<h2>Servers configuration</h2>

	<div class='alert <?= $data_server_state ?>' >
		<h3>NDOP data server</h3>
		<?php if($data_server_connection){ ?>
		Your data server is online, you can continue.
		<?php }elseif($data_server_info){ ?>
		Cannot connect to the data server, please retry.
		<?php }else{ ?>
		Please fill in the form.
		<?php } ?>


		<div class="accordion" id="accordion2">
			<div class="accordion-group">
				<form action="<?= $this->url('sql/config_data_server') ?>" method="POST">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
							Data server form
						</a>
					</div>
					<div id="collapseTwo" class="accordion-body collapse <?php if(!$data_server_connection){echo 'in';} ?>">
						<div class="accordion-inner">
							<label>Adress</label>
							<input name="data_server_address" type="text" placeholder="Ip of your NDOP data  server" value='<?= $data_server_address ?>'>
							<span class="help-block">Ex: 192.168.1.15 or www.myhostname.com</span>

							<label>Port</label>
							<input name="data_server_port" type="number" placeholder="Port of your NDOP data  server" value='<?= $data_server_port ?>'>
							<span class="help-block">Ex: 9005 by default</span>
							
							<button type="submit" class="btn">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div class='alert <?= $freegeoip_server_state ?>' >
		<h3>Freegoip server</h3>
		<?php if($freegeoip_server_connection){ ?>
		The freegeoip server is online, you can continue.
		<?php }elseif($freegeoip_server_info){ ?>
		Cannot connect to the freegeoip server, please retry.
		<?php }else{ ?>
		Please fill in the form.
		<?php } ?>


		<div class="accordion" id="accordion3">
			<div class="accordion-group">
				<form action="<?= $this->url('sql/config_freegeoip_server') ?>" method="POST">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion3" href="#collapseThree">
							Freegoip server form
						</a>
					</div>
					<div id="collapseThree" class="accordion-body collapse <?php if(!$freegeoip_server_connection){echo 'in';} ?>">
						<div class="accordion-inner">
							<label>Adress</label>
							<input name="freegeoip_server_address" type="text" placeholder="Ip of your freegeoip  server" value='<?= $freegeoip_server_address ?>'>
							<span class="help-block">Ex: 192.168.1.15 or www.freegeoip.net</span>

							<label>Port</label>
							<input name="freegeoip_server_port" type="number" placeholder="Port of your freegeoip server" value='<?= $freegeoip_server_port ?>'>
							<span class="help-block">Ex: 8080 by default</span>
							
							<button type="submit" class="btn">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>


</div>
