<link href="<?php echo $this->asset('assets/css/drag_drop.css') ?>" rel="stylesheet">
<link href="<?php echo $this->asset('assets/css/module_editor.css') ?>" rel="stylesheet">

<script src="<?= $this->asset('assets/js/Widget.js') ?>" ></script>
<script src="<?= $this->asset('assets/js/drag_drop_module.js') ?>" ></script>

<div id='panel' >
	<div id='inline-wrapper'>

		<?php foreach ($widgets as $key => $value) { ?>
		<div class='module' draggable="true" id="widget_<?= $value['id'] ?>">
			<div class="legend" ><?= $value['name'] ?> </div>
			<img src="/widgets/<?= $value['folder_name'] ?>/thumbnail.png">
		</div>
		<?php } ?>
	</div>
</div>

<div id='pages'>
	<div>
		<button class="btn btn-large btn-primary btn-wide" type="button" id="save">Save this configuration</button>
		<button class="btn btn-large btn-inverse btn-wide" type="button" id="clear">Clear this configuration</button>
	</div>
	<p>
		<form class="form-inline">
			<input id="module_name" type="text" class="input-small" placeholder="Name" value='<?= $module["module_name"] ?>'>
			
			<textarea id="module_description" rows="1" placeholder="Description" ><?= $module["module_description"] ?></textarea>
		</form>
	</p>
	<div class="row-fluid" style="height:400px">
		<div class="span8 row-fluid" id="module_content">
			<div class='height-half' id='first_line'>
			</div>
			<div class='height-half' id='second_line'>
			</div>
		</div>

		<div class="span4" id="widget_param">
			 
			    
			  	

		</div>
	</div>	
</div>

<input type="hidden" id="id_module" value="<?= $this['request.module'] ?>">
