<div class="hero-unit">
  <h1>Welcome to <strong>NDOP</strong></h1>
  <p>
    Congratulations! You have successfully installed NDOP.
    Now you have to configure your application. Go to the 
    <a href="<?= $this->url('config') ?>">Configuration page</a>!
    
  </p>
  <p><a target=_blank class="btn btn-large" href="http://github.com/OlivierB/Network-Display-On-Pi">Read the documentation on Github &raquo;</a></p>
</div>


