<link href="<?= $this->asset('assets/css/masonry.css') ?>" rel="stylesheet">
<script src="<?= $this->asset('assets/js/masonry.pkgd.min.js') ?>"></script>
<script src="<?= $this->asset('assets/js/masonry.perso.js') ?>"></script>



<div class="hero-unit">
	<h1>Modules <strong>customization</strong></h1>
	<p>Here you can choose what your modules will look like and define their parameters.</p>

	<p>
		<p>
			<a class="btn btn-primary btn-large" href="<?= $this->url('modules/editor') ?>">
				Create new module
			</a>
		</p>
	</p>
</div>

<div id="container" >
    <?php foreach ($modules as $key => $value){ ?>
    <div class="masonry">
    	<div class="thumbnail">
	        <!-- <img src="../modules/<?= $value['folder_name'] ?>/thumbnail.png" alt=""> -->
	        <div class="caption">
				<h3><?= $value['name'] ?></h3>
				<p><?= $value['description'] ?></p>
				
			</div>
			<a class="btn" href="<?= $this->url('modules/editor/'.$value['folder_name']) ?>" > Configure</a>
		</div>
   </div>
   <?php } ?>
</div>


