<link href="<?= $this->asset('assets/css/masonry.css') ?>" rel="stylesheet">
<link href="<?= $this->asset('assets/css/module_viewer.css') ?>" rel="stylesheet">

<script src="<?= $this->asset('assets/js/masonry.pkgd.min.js') ?>"></script>
<script src="<?= $this->asset('assets/js/masonry.perso.js') ?>"></script>
<script src="<?= $this->asset('assets/js/module_viewer.js') ?>"></script>


<div class="hero-unit">
	<h1>Modules <strong>customization</strong></h1>
	<p>Here you can choose what your modules will look like and define their parameters.</p>

	<p>
		<p>
			<a class="btn btn-primary btn-large" href="<?= $this->url('modules/editor') ?>">
				Create new module
			</a>
		</p>
	</p>
</div>

<div id="container" >
    <?php foreach ($modules as $key => $value){ ?>
    <div class="masonry">
    	<div class="thumbnail">
    		<i id='suppr<?= $value['id'] ?>' class="suppr icon-remove"></i>
	        <img src="<?= $this->asset('assets/images/module_thumbnail/'.$value['id'].'.png') ?>">
	        <div class="caption">
				<h3><?= $value['name'] ?></h3>
				<p><?= $value['description'] ?></p>
				
			</div>
			<a class="btn" href="<?= $this->url('modules/editor/'.$value['id']) ?>" > Configure</a>
		</div>
   </div>
   <?php } ?>
</div>


