<form action="<?= $this->url('sql/save_slide_config') ?>" method="POST">
  <fieldset>
    <legend>Configure your slides behaviour</legend>
    <label>Interval</label>
    <input type="number" name="interval" value="<?= $interval?>">
    <span class="help-block">Interval for each slide when the slideshow is on auto-playing.</span>
    <label class="checkbox">
      <input type="checkbox" name="auto_start" <?= $auto_start?>> Auto start : The slide show will start as soon as the page is loaded.
    </label>
    <label class="checkbox">
      <input type="checkbox" name="pause_on_hover" <?= $pause_on_hover?>> Pause on hover : The slideshow will pause if a cursor is over the page.
    </label>
    <button type="submit" class="btn">Submit</button>
  </fieldset>
</form>